apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: news
spec:
  schedule: "30 5,9,13,17,21 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: news
              image: gcr.io/intricate-mix-237607/news:0.1
          restartPolicy: OnFailure
